# Site settings
title: Gabriele Salvo
description: My Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Gabriele Salvo
user_description: YOUR BLOG OR PORTFOLIO HUSTLE FREE, NO MAINTENANCE COST, NO MONTHLY FEE, JUST WHAT YOU NEED.
Yes, you read that right, I build static website(Blog and portfolio mainly)  that require no cost offering you high security
and speed. You can even have your custom domain name (purchased separately at godaddy for example) or just use the default one (that you choose). 
I can provide you a professional portfolio or blog (even more if doable), fast and easy.
user_title: Front-End Developer
email: gab.salvo@outlook.it
twitter_username: https://twitter.com/gab_salvo
github_username: https://github.com/gabriele-salvo

# Google-analytics
google-analytics:
  id: "UA-162814431-4"

exclude: ['package.json', 'src' , 'node_modules']
