# Site settings
title: Gabriele Salvo
description: My Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Gabriele Salvo
user_description: Enthusiast Blog/Portfolio maker 
user_title: Front-End Developer
email: gab.salvo@outlook.it
twitter_username: gab_salvo
github_username:  gabriele-salvo

# Google-analytics
google-analytics:
  id: "UA-162814431-4"

exclude: ['package.json', 'src' , 'node_modules']
